### ISSUE TITLE
Port shouldn't be mandatory or have a default value

### ISSUE THREAD

**Issue by MisterKamran** [adamcin/net.adamcin.recap#2]
When configuring new addresses in the Address Book, a Port number is either required or set by default to 4502.  Not all instances have port numbers assigned to them and could just have a domain name only.

**Comment by adamcin** [comment]
@MisterKamran Thanks to @nteodori's contribution, I have added a "Quick Recap" feature to Recap version 1.0.0. You can now paste a URL into a field on the landing page to quickly configure an address based on the standard URL rules you would expect.
