### ISSUE TITLE
Oak mandatory properties

### ISSUE THREAD

**Issue by MisterJpa** [adamcin/net.adamcin.recap#7]
Hi, 

Thank you for this plugin. 

I'm getting the following issue:
Failed to save remaining changes. OakConstraint0021: /........./cq5dam.low.640.480.jpg/jcr:content[[nt:resource]]: Mandatory property jcr:data not found in a new node

I'm trying to transfer some content from an CQ5.4 to an AEM 6.0, this mean from CRX2.2 to CRX Oak 1.0.5.
The node in the CQ5.4 have the property jcr:data with a valid binary in it.

Do you have any idea of why it didn't work ?

Thanks and best regards,

MisterJpa

**Comment by adamcin** [comment]
@MisterJpa @sgu222e @muralikrishna1979  @akrivitzky  @nteodori  The issue appears to be in Oak. https://issues.apache.org/jira/browse/OAK-2052 describes the issue. Adobe released CQ-6.0.0-HOTFIX-5659 in December which has resolved the issue in my local testing. If you cannot install the hotfix, a workaround for AEM 5.6 to 6.0 migrations is to install Recap in the AEM 5.6 environment and perform the same transfer with the Reverse option checked, to push the content to the AEM 6.0 environment.

**Comment by akrivitzky** [comment]
I actually was looking at this on Friday, and came to the same conclusion.  I was wondering if a special Oak session was needed in your code, but gave up working on it for the weekend.  Just goes to show one should have the latest hotfixes applied.  I was able to confirm that applying the HOTFIX-5659 and the latest recap v1.0.0 fixed the issue in my sandbox.  Thanks Mark.
--Aaron

**Comment by adamcin** [comment]
Great, thanks for confirming, @akrivitzky.

**Comment by sgu222e** [comment]
I can also confirm it's working.
Thanks Mark.

**Comment by rakeshkonda** [comment]
I am seeing the same issue in AEM 6.1. Does AEM 6.1 also need the hot fix?
Could you please point me to the hot fix source..

**Comment by WegDamit** [comment]
The hotfix is oak 1.0.9. 
But the issue is still there in aem 6.1 with oak 1.2.4.
Any ideas on how to fix this?

**Comment by pulijalahari** [comment]
I see the following issue on AEM 6.1.. Should i apply any hotfixes on AEM 61?

31.03.2016 14:03:27.703 *ERROR* [0:0:0:0:0:0:0:1 [1459447407698] POST /home/users/l/lBsnzBvLsi3712xNQaPu/recapAddresses/* HTTP/1.1] org.apache.sling.servlets.post.impl.operations.ModifyOperation Exception during response processing.
javax.jcr.nodetype.ConstraintViolationException: No matching property definition: sling:resourceType = recap/components/addressbook/address
	at org.apache.jackrabbit.oak.jcr.delegate.NodeDelegate.setProperty(NodeDelegate.java:522)
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$35.perform(NodeImpl.java:1335)
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$35.perform(NodeImpl.java:1324)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:216)
	at org.apache.jackrabbit.oak.jcr.session.ItemImpl.perform(ItemImpl.java:113)
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.internalSetProperty(NodeImpl.java:1324)
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.setProperty(NodeImpl.java:426)
	at org.apache.sling.servlets.post.impl.helper.SlingPropertyValueHandler.store(SlingPropertyValueHandler.java:592)
	at org.apache.sling.servlets.post.impl.helper.SlingPropertyValueHandler.setPropertyAsIs(SlingPropertyValueHandler.java:305)
	at org.apache.sling.servlets.post.impl.helper.SlingPropertyValueHand
