### ISSUE TITLE
Replication

### ISSUE THREAD

**Issue by chadlnc** [adamcin/net.adamcin.recap#8]
First off, thanks for the work on this project, it has worked well for us in testing.

We ran a bigger job last night and we have two replication agents that go to the same publisher for different purposes, but it looks like recap is pushing replication to both queues, essentially doubling up the replication. Is there a way to limit which replication agents it uses or to not use them at all? Would stopping the recap replication bundle stop replication completely without any harmful effects to recap as a whole? We're thinking if we can't limit the replication agents, we might just kill the recap replication bundle then run a separate recap job from a production publisher down to the dev publisher.

**Comment by adamcin** [comment]
Recap core shouldn't have a dependency on the replication module, so I think it will still work if you stop the replication bundle. If you shutdown the replication bundle without clearing the replication queues, though, you may either see a lot of failed job messages in the error log.

You might be able to use different replication agent user ids with different permissions to let one recap queue handle one content tree, and let the other queue handle another tree.

**Comment by chadlnc** [comment]
That's not a bad idea. Thanks for the input.
